//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_ProyectoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS
    {
        internal List<PRODUCTOS> ProductosDisponibles;

        public int idFactura { get; set; }
        public System.DateTime fecha { get; set; }
        public int idCliente { get; set; }
        public int idMetodoPago { get; set; }
        public double impuesto { get; set; }
        public double subtotal { get; set; }
        public double total { get; set; }
        public int idProducto { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual METODOS_PAGO METODOS_PAGO { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
